[package]
name = "sifu-mod-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.0"
egui = "0.31.0"
msgbox = "0.7.0"
rar = "0.2.0"
rfd = "0.15.2"
serde = {version = "1.0.218", features = ["derive"]}
toml = "0.8.20"
win-msgbox = "0.2.1"
zip = "2.2.3"
